@startuml
interface IClassService {
    !ifdef CLASS_SERVICE_ISLECTUREROROWNERINCLASS
    +  IsLecturerOrOwnerInClass(classId:Guid): Task<bool>
    !endif
    !ifdef CLASS_SERVICE_ISUSERINCLASS
    +  IsUserInClass(classId:Guid): Task<bool>
    !endif
    !ifdef CLASS_SERVICE_GETCLASSOWNERACCESS
    +  GetClassOwnerAccess(classId:Guid, cancellationToken:CancellationToken): Task<(bool, Class)>
    !endif
}
@enduml