@startuml
actor User
participant "Question Set List UI" as UI <<UI>>
participant ":QuestionSetEndpoints" as QuestionSetEndpoints <<Controller>>
participant ":SearchRecentQuestionSetQueryHandler" as SearchRecentQuestionSetQueryHandler <<Handler>>
participant ":ApplicationDbContext" as ApplicationDbContext <<DbContext>>
participant Database

note right of SearchRecentQuestionSetQueryHandler
  Managed by MediatR
end note

note right of ApplicationDbContext
  Managed by IoC
end note

User -> UI : Request recent question sets
activate UI
UI -> QuestionSetEndpoints : GET /api/QuestionSet/Recent
activate QuestionSetEndpoints
QuestionSetEndpoints -> SearchRecentQuestionSetQueryHandler : Handle(SearchRecentQuestionSetQuery)
deactivate QuestionSetEndpoints
activate SearchRecentQuestionSetQueryHandler
SearchRecentQuestionSetQueryHandler -> ApplicationDbContext : Query recent QuestionSets by UserId
deactivate SearchRecentQuestionSetQueryHandler
activate ApplicationDbContext
ApplicationDbContext -> Database : Select recent QuestionSets
deactivate ApplicationDbContext
activate Database
Database --> ApplicationDbContext : QuestionSets
deactivate Database
activate ApplicationDbContext
ApplicationDbContext --> SearchRecentQuestionSetQueryHandler : QuestionSets
deactivate ApplicationDbContext
activate SearchRecentQuestionSetQueryHandler
SearchRecentQuestionSetQueryHandler -> QuestionSetEndpoints : PaginatedList<QuestionSetForListResponseDto>
deactivate SearchRecentQuestionSetQueryHandler
activate QuestionSetEndpoints
QuestionSetEndpoints --> UI : 200 OK (ApiResponse<PaginatedList<QuestionSetForListResponseDto>>)
deactivate QuestionSetEndpoints
UI -> User : Show recent question sets
deactivate UI

@enduml