@startuml
actor User
participant "Edit Question Set UI" as UI <<UI>>
participant ":QuestionSetEndpoints" as QuestionSetEndpoints <<Controller>>
participant ":UpdateQuestionSetCommandHandler" as UpdateQuestionSetCommandHandler <<Handler>>
participant ":QuestionSetService" as QuestionSetService <<Service>>
participant ":ApplicationDbContext" as ApplicationDbContext <<DbContext>>
participant Database

note right of UpdateQuestionSetCommandHandler
  Managed by MediatR
end note

note right of QuestionSetService
  Managed by IoC
end note

note right of ApplicationDbContext
  Managed by IoC
end note

User -> UI : Edit info, click "Save"
activate UI
UI -> QuestionSetEndpoints : PATCH /api/QuestionSet/{id}
activate QuestionSetEndpoints
QuestionSetEndpoints -> UpdateQuestionSetCommandHandler : Handle(UpdateQuestionSetCommand)
deactivate QuestionSetEndpoints
activate UpdateQuestionSetCommandHandler
UpdateQuestionSetCommandHandler -> QuestionSetService : GetActiveQuestionSet(questionSetId)
deactivate UpdateQuestionSetCommandHandler
activate QuestionSetService
QuestionSetService -> ApplicationDbContext : Query QuestionSet
deactivate QuestionSetService
activate ApplicationDbContext
ApplicationDbContext -> Database : Query QuestionSet
deactivate ApplicationDbContext
activate Database
Database --> ApplicationDbContext : QuestionSet
deactivate Database
activate ApplicationDbContext
ApplicationDbContext --> QuestionSetService : QuestionSet
deactivate ApplicationDbContext
activate QuestionSetService
QuestionSetService --> UpdateQuestionSetCommandHandler : QuestionSet
deactivate QuestionSetService
activate UpdateQuestionSetCommandHandler
alt Not found
    UpdateQuestionSetCommandHandler -> QuestionSetEndpoints : Error: QUESTION_SET_NOT_FOUND
    deactivate UpdateQuestionSetCommandHandler
    activate QuestionSetEndpoints
    QuestionSetEndpoints --> UI : 400 Bad Request { "error": "QUESTION_SET_NOT_FOUND" }
    deactivate QuestionSetEndpoints
    UI -> User : Display error: Question set not found
else Found
    activate UpdateQuestionSetCommandHandler
    UpdateQuestionSetCommandHandler -> QuestionSetService : CanUserEditQuestionSet(userId, questionSetId)
    deactivate UpdateQuestionSetCommandHandler
    activate QuestionSetService
    QuestionSetService -> ApplicationDbContext : Query Permission
    deactivate QuestionSetService
    activate ApplicationDbContext
    ApplicationDbContext -> Database : Query Permission
    deactivate ApplicationDbContext
    activate Database
    Database --> ApplicationDbContext : Permission
    deactivate Database
    activate ApplicationDbContext
    ApplicationDbContext --> QuestionSetService : Permission
    deactivate ApplicationDbContext
    activate QuestionSetService
    QuestionSetService --> UpdateQuestionSetCommandHandler : bool
    deactivate QuestionSetService
    activate UpdateQuestionSetCommandHandler
    alt No permission
        UpdateQuestionSetCommandHandler -> QuestionSetEndpoints : Error: COMMON_FORBIDDEN
        deactivate UpdateQuestionSetCommandHandler
        activate QuestionSetEndpoints
        QuestionSetEndpoints --> UI : 400 Bad Request { "error": "COMMON_FORBIDDEN" }
        deactivate QuestionSetEndpoints
        UI -> User : Display error: No permission
    else Allowed
        activate UpdateQuestionSetCommandHandler
        UpdateQuestionSetCommandHandler -> ApplicationDbContext : Update QuestionSet
        deactivate UpdateQuestionSetCommandHandler
        activate ApplicationDbContext
        ApplicationDbContext -> Database : Update QuestionSet
        deactivate ApplicationDbContext
        activate Database
        Database --> ApplicationDbContext : Success
        deactivate Database
        activate ApplicationDbContext
        ApplicationDbContext --> UpdateQuestionSetCommandHandler : Guid
        deactivate ApplicationDbContext
        activate UpdateQuestionSetCommandHandler
        UpdateQuestionSetCommandHandler -> QuestionSetEndpoints : Guid
        deactivate UpdateQuestionSetCommandHandler
        activate QuestionSetEndpoints
        QuestionSetEndpoints --> UI : 200 OK (ApiResponse<Guid>)
        deactivate QuestionSetEndpoints
        UI -> User : Display info: Update successful
    end
end
deactivate UI

@enduml