@startuml
top to bottom direction
'=====================DEFINE========================
!define REGISTER
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class RegisterUserCommand {
    +Email: string
    +Password: string
}
class RegisterUserCommandHandler {
    -IIdentityService _identityService
    +Handle(RegisterUserCommand, CancellationToken) : Task<string>
}
'=====================ENDPOINT========================
class AuthenticationEndpoints  {
    +RegisterUser(RegisterUserCommand, ISender) : Task<Ok<ApiResponse<string>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
RegisterUserCommand ..|> IRequest : implements
RegisterUserCommandHandler ..> IIdentityService : inject
RegisterUserCommandHandler ..> RegisterUserCommand :  use
AuthenticationEndpoints ..> RegisterUserCommand : use
RegisterUserCommandHandler <.. ISender : sends to
RegisterUserCommandHandler ..|> IRequestHandler : implements
@enduml