@startuml
'=====================DEFINE========================
!define GOOGLE_REGISTER
!define GOOGLE_SERVICE
!define JWT
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================

class GoogleRegisterCommand {
    + AuthorizationCode : string
}
class GoogleRegisterCommandHandler {
    -IIdentityService _identityService
    -IApplicationDbContext _context
    +Handle(GoogleRegisterCommand, CancellationToken)
}
class AuthenticationEndpoints {
    +GoogleRegisterCommand(GoogleRegisterCommand, ISender, HttpContext, IOptions<JwtSettings>)
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GoogleRegisterCommand ..|> IRequest : implements
GoogleRegisterCommandHandler ..> IIdentityService : inject
GoogleRegisterCommandHandler ..> GoogleRegisterCommand :  use
AuthenticationEndpoints ..> GoogleRegisterCommand : use
GoogleRegisterCommandHandler <.. ISender : sends to
GoogleRegisterCommandHandler ..|> IRequestHandler : implements
AuthenticationEndpoints ..> JwtSettings : <<inject>>

@enduml