@startuml
'=====================DEFINE========================
!define REFRESH_TOKEN
!define JWT
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class RefreshTokenCommand {
    +string? AccessToken
    +string? RefreshToken
}
class RefreshTokenCommandHandler {
    -IIdentityService _identityService
    +Handle(RefreshTokenCommand, CancellationToken)
}
'=======================ENDPOINT========================
class AuthenticationEndpoints {
    +RefreshToken(RefreshTokenCommand, ISender, HttpContext, IOptions<JwtSettings>)
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GoogleLoginCommand ..|> IRequest : implements
GoogleLoginCommandHandler ..> IIdentityService : inject
GoogleLoginCommandHandler ..> GoogleLoginCommand :  use
AuthenticationEndpoints ..> GoogleLoginCommand : use
GoogleLoginCommandHandler <.. ISender : sends to
GoogleLoginCommandHandler ..|> IRequestHandler : implements
AuthenticationEndpoints ..> JwtSettings : <<inject>>
@enduml 