@startuml
'=====================DEFINE========================
!define REQUEST_EMAIL_VERIFICATION
!define EMAIL_SERVICE
'======================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=======================COMMAND========================
class RequestEmailVerificationCommand {
    +string Email
}
class RequestEmailVerificationCommandHandler {
    -IIdentityService _identityService
    +Handle(RequestEmailVerificationCommand, CancellationToken)
}
'=======================ENDPOINT========================
class AuthenticationEndpoints {
    +RequestEmailVerification(RequestEmailVerificationCommand, ISender)
}
'=======================RELATIONSHIP========================
!include zCommon.puml
RequestEmailVerificationCommand ..|> IRequest : implements
RequestEmailVerificationCommandHandler ..> IIdentityService : inject
RequestEmailVerificationCommandHandler ..> RequestEmailVerificationCommand :  use
AuthenticationEndpoints ..> RequestEmailVerificationCommand : use
RequestEmailVerificationCommandHandler <.. ISender : sends to
RequestEmailVerificationCommandHandler ..|> IRequestHandler : implements
@enduml 