@startuml
'=====================DEFINE========================
!define VERIFY_EMAIL
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=======================COMMAND========================
class VerifyEmailCommand {
    +string Email
    +string VerificationCode
}
class VerifyEmailCommandHandler {
    -IIdentityService _identityService
    +Handle(VerifyEmailCommand, CancellationToken)
}
'=======================ENDPOINT========================
class AuthenticationEndpoints {
    +VerifyEmail(VerifyEmailCommand, ISender)
}
'=====================RELATIONSHIP========================
!include zCommon.puml
VerifyEmailCommand ..|> IRequest : implements
VerifyEmailCommandHandler ..> IIdentityService : inject
VerifyEmailCommandHandler ..> VerifyEmailCommand :  use
AuthenticationEndpoints ..> VerifyEmailCommand : use
VerifyEmailCommandHandler <.. ISender : sends to
VerifyEmailCommandHandler ..|> IRequestHandler : implements
@enduml 