@startuml
'=====================DEFINE========================
!define REQUEST_PASSWORD_RESET
!define EMAIL_SERVICE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class RequestPasswordResetCommand {
    +string Email
}
class RequestPasswordResetCommandHandler {
    -IIdentityService _identityService
    +Handle(RequestPasswordResetCommand, CancellationToken)
}
'=====================ENDPOINT========================
class AuthenticationEndpoints {
    +RequestPasswordReset(RequestPasswordResetCommand, ISender)
}
'=====================RELATIONSHIP========================
!include zCommon.puml
RequestPasswordResetCommand ..|> IRequest : <<implements>>
RequestPasswordResetCommandHandler ..> IIdentityService : <<inject>>
RequestPasswordResetCommandHandler ..> RequestPasswordResetCommand :  <<use>>
AuthenticationEndpoints ..> RequestPasswordResetCommand : <<use>>
RequestPasswordResetCommandHandler <.. ISender : <<sends to>>
RequestPasswordResetCommandHandler ..|> IRequestHandler : <<implements>>
@enduml