@startuml
'=====================DEFINE========================
!define RESET_PASSWORD
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=======================COMMAND========================
class ResetPasswordCommand {
    + Email: string
    + ResetCode: string
    + NewPassword : string
}
class ResetPasswordCommandHandler {
    -_identityService : IIdentityService
    +Handle(command: ResetPasswordCommand, cancellationToken: CancellationToken)
}
'=======================ENDPOINT========================
class AuthenticationEndpoints {
    +ResetPassword(command: ResetPasswordCommand, sender: ISender) : Task<Ok<ApiResponse<object>>>
}
'=======================RELATIONSHIP========================
!include zCommon.puml
ResetPasswordCommand ..|> IRequest : <<implements>>
ResetPasswordCommandHandler ..> IIdentityService : <<inject>>
ResetPasswordCommandHandler ..> ResetPasswordCommand :  <<uses>>
AuthenticationEndpoints ..> ResetPasswordCommand : <<uses>>
ResetPasswordCommandHandler <.. ISender : <<sends to>>
ResetPasswordCommandHandler ..|> IRequestHandler : <<implements>>
@enduml