@startuml
'=====================DEFINE========================
!define RESET_PASSWORD
'=====================IMPORT========================
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=======================COMMAND========================
class ResetPasswordCommand {
    +string Email
    +string ResetCode
    +string NewPassword
}
class ResetPasswordCommandHandler {
    -IIdentityService _identityService
    +Handle(ResetPasswordCommand, CancellationToken)
}
'=======================ENDPOINT========================
class AuthenticationEndpoints {
    +ResetPassword(ResetPasswordCommand, ISender)
}
'=======================RELATIONSHIP========================
!include zCommon.puml

@enduml