@startuml
'=====================DEFINE========================
!define CHANGE_PASSWORD
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class ChangePasswordCommand {
    +string CurrentPassword
    +string NewPassword
}
class ChangePasswordCommandHandler {
    -IIdentityService _identityService
    -IUser _currentUser
    +Handle(ChangePasswordCommand, CancellationToken)
}
'=====================ENDPOINT========================
class AuthenticationEndpoints  {
    +RegisterUser(RegisterUserCommand, ISender) : Task<Ok<ApiResponse<string>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
ChangePasswordCommand ..|> IRequest : implements
ChangePasswordCommandHandler ..> IIdentityService : inject
ChangePasswordCommandHandler ..> ChangePasswordCommand :  use
AuthenticationEndpoints ..> ChangePasswordCommand : use
ChangePasswordCommandHandler <.. ISender : sends to
ChangePasswordCommandHandler ..|> IRequestHandler : implements

@enduml 