@startuml
'=====================DEFINE========================
!define CHANGE_PASSWORD
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class ChangePasswordCommand {
    +string CurrentPassword
    +string NewPassword
}
class ChangePasswordCommandHandler {
    -IIdentityService _identityService
    -IUser _currentUser
    +Handle(ChangePasswordCommand, CancellationToken)
}
'=====================ENDPOINT========================
class AuthenticationEndpoints  {
    +ChangePassword(ChangePasswordCommand, ISender) : Task<Ok<ApiResponse<object>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
ChangePasswordCommand ..|> IRequest : <<implements>>
ChangePasswordCommandHandler ..> IIdentityService : <<inject>>
ChangePasswordCommandHandler ..> ChangePasswordCommand :  <<uses>>
AuthenticationEndpoints ..> ChangePasswordCommand : <<uses>>
ChangePasswordCommandHandler <.. ISender : <<sends to>>
ChangePasswordCommandHandler ..|> IRequestHandler : <<implements>>

@enduml 