@startuml
title Authentication | Change password
'=====================DEFINE========================
!define CHANGE_PASSWORD
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class ChangePasswordCommand {
    + CurrentPassword : string
    + NewPassword : string
}
class ChangePasswordCommandHandler {
    -_identityService : IIdentityService
    -_currentUser: IUser
    +Handle(command: ChangePasswordCommand, cancellationToken: CancellationToken)
}
'=====================ENDPOINT========================
class AuthenticationEndpoints  {
    +ChangePassword(command: ChangePasswordCommand, sender: ISender) : Task<Ok<ApiResponse<object>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
ChangePasswordCommand ..|> IRequest : <<implements>>
ChangePasswordCommandHandler ..> IIdentityService : <<inject>>
ChangePasswordCommandHandler ..> ChangePasswordCommand :  <<uses>>
AuthenticationEndpoints ..> ChangePasswordCommand : <<uses>>
ChangePasswordCommandHandler ..|> IRequestHandler : <<implements>>

@enduml 