@startuml
interface ITestTemplateService {
    !ifdef TEST_TEMPLATE_SERVICE_TRYCHECKQUESTIONACCESSFORTESTTEMPLATE
    +  TryCheckQuestionAccessForTestTemplate(questions:List<CreateUpdateQuestionDto>, cancellationToken:CancellationToken): Task
    !endif
    !ifdef TEST_TEMPLATE_SERVICE_CANDELETETESTTEMPLATE
    +  CanDeleteTestTemplate(testTemplateId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef TEST_TEMPLATE_SERVICE_CANEDITTESTTEMPLATE
    +  CanEditTestTemplate(testTemplateId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef TEST_TEMPLATE_SERVICE_CANVIEWTEMPLATE
    +  CanViewTesTemplate(testTemplateId:Guid): Task<bool>
    !endif
    !ifdef TEST_TEMPLATE_SERVICE_CHECKQUESTIONSFORUPDATE
    + CheckQuestionsForUpdate(updateQuestionDto:List<CreateUpdateQuestionDto>, updateQuestion:List<Question>): CheckUpdateQuestion
    !endif
}
@enduml