@startuml Logical ERD for AIQuizziz

' Entities
entity "User" {
  * Id
  --
  Email
  Balance
  TokenCount
}

entity "Role" {
  * Id
  --
  Name
}

entity "Class" {
  * Id
  --
  Name
}

entity "QuestionSet" {
  * Id
  --
  Name
  VisibilityMode
  QuestionCount
}

entity "Question" {
  * Id
  --
  Type
  QuestionText
  QuestionContent
  Score
}

entity "Test" {
  * Id
  --
  Name
  TimeStart
  TimeFinish
  TimeLimit
  GradeAttemptMethod
  GradeQuestionMethod
}

entity "Attempt" {
  * Id
  --
  TimeStart
  TimeFinish
  Score
}

entity "AttemptQuestion" {
  * Id
  --
  Order
  Score
  UserAnswer
}

entity "TestTemplate" {
  * Id
  --
  Name
}

entity "Folder" {
  * Id
  --
  Name
}

entity "Plan" {
  * Id
  --
  Name
  Price
  DayDuration
}

entity "TokenPackage" {
  * Id
  --
  Name
  Price
  TokenCount
}

entity "Comment" {
  * Id
  --
  Content
  IsDeleted
}

entity "TestGrade" {
  * Id
  --
  Score
}

entity "ClassInvitation" {
  * Id
  --
  Code
  TimeStart
  TimeEnd
}

entity "RefreshToken" {
  * Id
  --
  Token
  ExpireAt
}

entity "Tag" {
  * Id
  --
  Name
}






' Relationships
User }o--o{ Role : has
User }o--o{ Class : belongs to
Class }o--o{ QuestionSet : contains
QuestionSet ||--o{ Question : contains
User ||--o{ Attempt : takes
Test ||--o{ Attempt : has
Attempt ||--o{ AttemptQuestion : contains
AttemptQuestion }o--|| Question : references
Test }o--o{ Question : includes
TestTemplate ||--o{ Question : includes
Folder ||--o{ TestTemplate : contains
User }o--o{ Folder : has access to
User }o--o{ Plan : subscribes to
User }o--o{ TokenPackage : purchases
Question ||--o{ Comment : has
Comment ||--o{ Comment : replies to
User ||--o{ TestGrade : receives
Test ||--o{ TestGrade : has
Class ||--o{ ClassInvitation : issues
User }o--o{ ClassInvitation : joins 
User ||--o{ RefreshToken : owns
User }o--o{ QuestionSet : has access to
QuestionSet }o--o{ Tag : has





@enduml