@startuml
title Users | BanAccountCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IUser.puml
!include ../../common/service/IIdentityService.puml
!include ../../Domain/Constants/Roles.puml

'=====================CLASSES========================

class BanAccountCommand {
    + UserId : Guid <<get>> <<set>>
    + IsBanned : bool <<get>> <<set>>
}

class BanAccountCommandValidator {
    + BanAccountCommandValidator()
}

class BanAccountCommandHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    - <<readonly>> _identityService : IIdentityService
    + BanAccountCommandHandler(context:IApplicationDbContext, user:IUser, identityService:IIdentityService)
    + <<async>> Handle(rq:BanAccountCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class UserEndpoints  {
    + <<async>> BanAccount(userId:Guid, isBanned:bool, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}

'=====================RELATIONSHIP========================
BanAccountCommand ..|> IRequest : <<implements>>
BanAccountCommandHandler ..> BanAccountCommand : <<uses>>
BanAccountCommandHandler ..|> IRequestHandler : <<implements>>
UserEndpoints ..> BanAccountCommand : <<uses>>
BanAccountCommandHandler ..> IApplicationDbContext : <<inject>>
BanAccountCommandHandler ..> IUser : <<inject>>
BanAccountCommandHandler ..> IIdentityService : <<inject>>
BanAccountCommandValidator ..> BanAccountCommand : <<validates>>
BanAccountCommand --> Roles : <<uses>>
!include zCommon.puml

@enduml