@startuml
title Users | ChangePasswordCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
!include ../../common/service/IUser.puml

'=====================CLASSES========================

class ChangePasswordCommand {
    + CurrentPassword : string
    + NewPassword : string
}

class ChangePasswordCommandValidator {
    + ChangePasswordCommandValidator()
}

class ChangePasswordCommandHandler {
    -  _identityService : IIdentityService
    -  _currentUser : IUser
    + ChangePasswordCommandHandler(identityService:IIdentityService, currentUser:IUser)
    +  Handle(request:ChangePasswordCommand, cancellationToken:CancellationToken) : Task
}

'=====================ENDPOINT========================
class UserEndpoints  {
    +  ChangePassword(request:ChangePasswordCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}

'=====================RELATIONSHIP========================
ChangePasswordCommand ..|> IRequest : <<implements>>
ChangePasswordCommandHandler ..> ChangePasswordCommand : <<uses>>
ChangePasswordCommandHandler ..|> IRequestHandler : <<implements>>
UserEndpoints ..> ChangePasswordCommand : <<uses>>
ChangePasswordCommandHandler ..> IIdentityService : <<inject>>
ChangePasswordCommandHandler ..> IUser : <<inject>>
ChangePasswordCommandValidator ..> ChangePasswordCommand : <<validates>>
!include zCommon.puml

@enduml