@startuml
title Users | ChangePasswordCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/FluentValidation.puml
!include ../../common/Interfaces/IIdentityService.puml
!include ../../common/Interfaces/IUser.puml
!include ../../common/Security/Authorize.puml

'=====================CLASSES========================

class ChangePasswordCommand {
    + CurrentPassword : string <<get>> <<set>>
    + NewPassword : string <<get>> <<set>>
}

class ChangePasswordCommandValidator {
    + ChangePasswordCommandValidator()
}

class ChangePasswordCommandHandler {
    - <<readonly>> _identityService : IIdentityService
    - <<readonly>> _currentUser : IUser
    + ChangePasswordCommandHandler(identityService:IIdentityService, currentUser:IUser)
    + <<async>> Handle(request:ChangePasswordCommand, cancellationToken:CancellationToken) : Task
}

'=====================RELATIONSHIP========================
ChangePasswordCommand ..|> IRequest : <<implements>>
ChangePasswordCommandHandler ..> ChangePasswordCommand : <<uses>>
ChangePasswordCommandHandler ..|> IRequestHandler : <<implements>>
ChangePasswordCommandHandler ..> IIdentityService : <<inject>>
ChangePasswordCommandHandler ..> IUser : <<inject>>
ChangePasswordCommandValidator ..> ChangePasswordCommand : <<validates>>
@enduml