@startuml

'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/EndpointClasses.puml
!include ../../Users/Dto/UserForSelectionDto.puml

'=====================CLASSES========================

class SearchUserForSelectionQuery {
    + Email : string?
}

class SearchUserForSelectionQueryHandler {
    -  _context : IApplicationDbContext
    + SearchUserForSelectionQueryHandler(context:IApplicationDbContext)
    +  Handle(request:SearchUserForSelectionQuery, cancellationToken:CancellationToken) : Task<List<UserForSelectionDto>>
}

'=====================ENDPOINT========================
class UserEndpoints  {
    +  SearchUserForSelection(request:SearchUserForSelectionQuery, sender:ISender) : Task<Ok<ApiResponse<List<UserForSelectionDto>>>>
}

'=====================RELATIONSHIP========================
SearchUserForSelectionQuery ..|> IRequest : <<implements>>
SearchUserForSelectionQueryHandler ..> SearchUserForSelectionQuery : <<uses>>
SearchUserForSelectionQueryHandler ..|> IRequestHandler : <<implements>>
UserEndpoints ..> SearchUserForSelectionQuery : <<uses>>
SearchUserForSelectionQueryHandler ..> IApplicationDbContext : <<inject>>
SearchUserForSelectionQuery --> UserForSelectionDto : <<returns>>
SearchUserForSelectionQueryHandler ..> UserForSelectionDto : <<uses>>
!include zCommon.puml

@enduml