@startuml
title Users | SearchAllAccountQuery
'=====================DEFINE========================
!define CHANGE_PASSWORD
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml

'=====================CLASSES========================

class UserForListDto {
    + Id : Guid <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + FullName : string? <<get>> <<set>>
    + Token : long <<get>> <<set>>
    + Balance : long <<get>> <<set>>
    + IsBanned : bool <<get>> <<set>>
    + Role : string? <<get>> <<set>>
}

class SearchAllAccountQuery {
    + Keyword : string? <<get>> <<set>>
    + FieldName : string? <<get>> <<set>>
    + PageNumber : int <<get>> <<set>>
    + PageSize : int <<get>> <<set>>
    + IsBanned : bool? <<get>> <<set>>
    + Role : string? <<get>> <<set>>
}

class SearchUserDto {
    + Keyword : string? <<get>> <<set>>
    + FieldName : string? <<get>> <<set>>
    + PageNumber : int <<get>> <<set>>
    + PageSize : int <<get>> <<set>>
    + IsBanned : bool? <<get>> <<set>>
    + Role : string? <<get>> <<set>>
}

class SearchAllAccountQueryValidator {
    + SearchAllAccountQueryValidator()
}

class GetAllAccountCommandHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _identityService : IIdentityService
    + GetAllAccountCommandHandler(context:IApplicationDbContext, identityService:IIdentityService)
    + <<async>> Handle(rq:SearchAllAccountQuery, cancellationToken:CancellationToken) : Task<PaginatedList<UserForListDto>>
}

'=====================ENDPOINT========================
class UserEndpoints  {
    + <<async>> SearchAllAccount(request:SearchAllAccountQuery, sender:ISender) : Task<Ok<ApiResponse<PaginatedList<UserForListDto>>>>
}

'=====================RELATIONSHIP========================
SearchAllAccountQuery ..|> IRequest : <<implements>>
GetAllAccountCommandHandler ..> SearchAllAccountQuery : <<uses>>
GetAllAccountCommandHandler ..|> IRequestHandler : <<implements>>
UserEndpoints ..> SearchAllAccountQuery : <<uses>>
GetAllAccountCommandHandler ..> IApplicationDbContext : <<inject>>
GetAllAccountCommandHandler ..> IIdentityService : <<inject>>
SearchAllAccountQueryValidator ..> SearchAllAccountQuery : <<validates>>
GetAllAccountCommandHandler ..> UserForListDto : <<uses>>
SearchAllAccountQuery --> UserForListDto : <<returns>>
SearchAllAccountQuery --> SearchUserDto : <<uses>>
!include zCommon.puml

@enduml