@startuml
title Users | SearchAllAccountQuery
'=====================DEFINE========================
!define CHANGE_PASSWORD
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml

'=====================CLASSES========================

class UserForListDto {
    + Id : Guid
    + Email : string
    + FullName : string?
    + Token : long
    + Balance : long
    + IsBanned : bool
    + Role : string?
}

class SearchAllAccountQuery {
    + Keyword : string?
    + FieldName : string?
    + PageNumber : int
    + PageSize : int
    + IsBanned : bool?
    + Role : string?
}

class SearchUserDto {
    + Keyword : string?
    + FieldName : string?
    + PageNumber : int
    + PageSize : int
    + IsBanned : bool?
    + Role : string?
}

class SearchAllAccountQueryValidator {
    + SearchAllAccountQueryValidator()
}

class GetAllAccountCommandHandler {
    -  _context : IApplicationDbContext
    -  _identityService : IIdentityService
    + GetAllAccountCommandHandler(context:IApplicationDbContext, identityService:IIdentityService)
    +  Handle(rq:SearchAllAccountQuery, cancellationToken:CancellationToken) : Task<PaginatedList<UserForListDto>>
}

'=====================ENDPOINT========================
class UserEndpoints  {
    +  SearchAllAccount(request:SearchAllAccountQuery, sender:ISender) : Task<Ok<ApiResponse<PaginatedList<UserForListDto>>>>
}

'=====================RELATIONSHIP========================
SearchAllAccountQuery ..|> IRequest : <<implements>>
GetAllAccountCommandHandler ..> SearchAllAccountQuery : <<uses>>
GetAllAccountCommandHandler ..|> IRequestHandler : <<implements>>
UserEndpoints ..> SearchAllAccountQuery : <<uses>>
GetAllAccountCommandHandler ..> IApplicationDbContext : <<inject>>
GetAllAccountCommandHandler ..> IIdentityService : <<inject>>
SearchAllAccountQueryValidator ..> SearchAllAccountQuery : <<validates>>
GetAllAccountCommandHandler ..> UserForListDto : <<uses>>
SearchAllAccountQuery --> UserForListDto : <<returns>>
SearchAllAccountQuery --> SearchUserDto : <<uses>>
!include zCommon.puml

@enduml