@startuml
title Users | UpdateUserInfoCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml

'=====================CLASSES========================

class UpdateUserInfoCommand {
    + FullName : string
}

class UpdateUserInfoCommandValidator {
    + UpdateUserInfoCommandValidator()
}

class UpdateUserInfoCommandHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    + UpdateUserInfoCommandHandler(context:IApplicationDbContext, user:IUser)
    +  Handle(request:UpdateUserInfoCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class UserEndpoints  {
    +  UpdateUserInfo(request:UpdateUserInfoCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}

'=====================RELATIONSHIP========================
UpdateUserInfoCommand ..|> IRequest : <<implements>>
UpdateUserInfoCommandHandler ..> UpdateUserInfoCommand : <<uses>>
UpdateUserInfoCommandHandler ..|> IRequestHandler : <<implements>>
UserEndpoints ..> UpdateUserInfoCommand : <<uses>>
UpdateUserInfoCommandHandler ..> IApplicationDbContext : <<inject>>
UpdateUserInfoCommandHandler ..> IUser : <<inject>>
UpdateUserInfoCommandValidator ..> UpdateUserInfoCommand : <<validates>>
!include zCommon.puml

@enduml