@startuml
interface ITestService {
    !ifdef TEST_SERVICE_CANCREATETEST
    +  CanCreateTest(classId:Guid): Task<bool>
    !endif
    !ifdef TEST_SERVICE_CANVIEWOREDITTEST
    +  CanViewOrEditTest(classId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef TEST_SERVICE_QUESTIONACCESSANDCOMPAREFORTEST
    +  QuestionAccessAndCompareForTest(questions:List<CreateUpdateQuestionDto>, cancellationToken:CancellationToken): Task<List<Guid>>
    !endif
    !ifdef TEST_SERVICE_TRYCHECKCANATTEMPTTEST
    +  TryCheckCanAttemptTest(test:Test): Task
    !endif
    !ifdef TEST_SERVICE_GETROLEUSERINTEST
    +  GetRoleUserInTest(test:Test): Task<ClassShareMode>
    !endif
    !ifdef TEST_SERVICE_CANVIEWHISTORYOFTEST
    +  CanViewHistoryOfTest(classId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef TEST_SERVICE_CHECKQUESTIONSFORUPDATE
    + CheckQuestionsForUpdate(updateQuestionDto:List<CreateUpdateQuestionDto>, updateQuestion:List<Question>): CheckUpdateQuestion
    !endif
}
@enduml