@startuml
interface IFolderTestService {
    !ifdef FOLDER_TEST_SERVICE_CANDELETEOREDITFOLDERTEST
    +  CanDeleteOrEditFolderTest(folderTestId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef FOLDER_TEST_SERVICE_ISOWNEROREDITOR
    +  IsOwnerOrEditor(folderTestId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef FOLDER_TEST_SERVICE_TRYCANUSETESTEMPLATE
    +  TryCanUseTesTemplate(testTemplateId:Guid): Task
    !endif
}
@enduml