@startuml
class "PaginatedList<T>" as PaginatedList {
    + Items : IReadOnlyCollection<T>
    + PageNumber : int
    + TotalPages : int
    + TotalCount : int
    + PageSize : int
    + HasPreviousPage : bool
    + HasNextPage : bool
    + PaginatedList(items:IReadOnlyCollection<T>, count:int, pageNumber:int, pageSize:int)
    + {static} CreateAsync(source:IQueryable<T>, pageNumber:int, pageSize:int) : Task<PaginatedList<T>>
    + {static} Create(source:List<T>, pageIndex:int, pageSize:int) : PaginatedList<T>
}
@enduml