@startuml
' Các entity chính liên quan đến QuestionSet
class QuestionSet {
    + Id : Guid
    + Name : string
    + Description : string
    + VisibilityMode : QuestionSetVisibilityMode
    + QuestionCount : int
    + IsDeleted : bool
    + Questions : List<Question>
}

class Question {
    + Id : Guid
    + QuestionSetId : Guid?
    + Type : QuestionType
    + QuestionText : string?
    + TextFormat : TextFormat
    + ExplainText : string?
    + Score : float
    + DataJson : string?
    + IsDeleted : bool
    + Data : object?
    + QuestionSet : QuestionSet
    + Comments : List<Comment>
    + UserQuestionSetHistories : List<UserQuestionSetHistory>
    + TestTemplateQuestions : List<TestTemplateQuestion>
    + TestVersionQuestions : List<TestVersionQuestion>
    + AttemptQuestions : List<AttemptQuestion>
}

class QTypeMultipleChoice {
    + Id : Guid
    + Text : string
    + IsAnswer : bool
    + ShuffleOrder : short
}
class QTypeMatching {
    + Id : Guid
    + Text : string
    + AnswerId : string?
    + ShuffleOrder : short
}
class QTypeOrderingItem {
    + Id : Guid
    + Text : string
    + CorrectOrder : int
    + ShuffleOrder : short
}
class QTypeShortAnswer {
    + Answer : string
}

QuestionSet "1" --* "*" Question : Questions
Question --* QTypeMultipleChoice
Question --* QTypeMatching
Question --* QTypeOrderingItem
Question --* QTypeShortAnswer
@enduml 