@startuml
class TestTemplate {
    + Id : Guid
    + Name : string
    + IsDeleted : bool
    + TestTemplateQuestions : List<TestTemplateQuestion>
    + TestTemplateUsers : List<TestTemplateUser>
    + FolderTestTemplates : List<FolderTestTemplate>
}
@enduml 