@startuml

'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../dtos/CreateUpdateQuestionDto.puml
'=====================COMMAND========================
class CreateQuestionSetCommand {
    + Name : string?
    + Description : string?
    + Questions : List<CreateUpdateQuestionDto>
}



class CreateQuestionSetCommandHandler {
    -  _dbContext : IApplicationDbContext
    + CreateQuestionSetCommandHandler(dbContext:IApplicationDbContext)
    +  Handle(request:CreateQuestionSetCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    +  CreateQuestionSet(command:CreateQuestionSetCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateQuestionSetCommand ..|> IRequest : <<implements>>
CreateQuestionSetCommandHandler ..> CreateQuestionSetCommand :  <<uses>>
QuestionSetEndpoints ..> CreateQuestionSetCommand : <<uses>>
CreateQuestionSetCommandHandler ..|> IRequestHandler : <<implements>>
CreateQuestionSetCommand --* CreateUpdateQuestionDto : <<uses>>
'=====INJECT
CreateQuestionSetCommandHandler ..> IApplicationDbContext : <<inject>>
'=====INJECT
@enduml