@startuml

'=====================DEFINE========================
!define QUESTIONSET_SERVICE_CANUSERDELETE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include ../Services/IQuestionSetService.puml
'=====================COMMAND========================
class DeleteQuestionSetCommand {
    + QuestionSetId : Guid
}
class DeleteQuestionSetCommandHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    -  _questionSetService : IQuestionSetService
    + DeleteQuestionSetCommandHandler(context:IApplicationDbContext, user:IUser, questionSetService:IQuestionSetService)
    +  Handle(request:DeleteQuestionSetCommand, cancellationToken:CancellationToken) : Task<Unit>
}
'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    +  DeleteQuestionSet(questionSetId:Guid, sender:ISender) : Task<Ok<ApiResponse<Unit>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
DeleteQuestionSetCommand ..|> IRequest : <<implements>>
DeleteQuestionSetCommandHandler ..> DeleteQuestionSetCommand :  <<uses>>
QuestionSetEndpoints ..> DeleteQuestionSetCommand : <<uses>>
DeleteQuestionSetCommandHandler ..|> IRequestHandler : <<implements>>
'=====INJECT
DeleteQuestionSetCommandHandler ..> IApplicationDbContext : <<inject>>
DeleteQuestionSetCommandHandler ..> IQuestionSetService : <<inject>>
DeleteQuestionSetCommandHandler ..> IUser : <<inject>>
'=====INJECT
@enduml