@startuml
title QuestionSet | GetQuestionSetDetailQuery
'=====================DEFINE========================
!define QUESTIONSET_SERVICE_CANUSERVIEW
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IUser.puml
!include ../Services/IQuestionSetService.puml
!include ../dtos/QuestionSetDetailDto.puml
'=====================COMMAND========================
class GetQuestionSetDetailQuery {
    + QuestionSetId : Guid <<get>> <<set>>
}

class GetQuestionSetDetailQueryHandler {
    - _questionSetService : IQuestionSetService
    - _user : IUser
    + GetQuestionSetDetailQueryHandler(questionSetService:IQuestionSetService, user:IUser)
    + <<async>> Handle(request:GetQuestionSetDetailQuery, cancellationToken:CancellationToken) : Task<QuestionSetDetailDto>
}
'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    + <<async>> GetQuestionSetDetail(questionSetId:Guid, sender:ISender) : Task<Ok<ApiResponse<QuestionSetDetailDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetQuestionSetDetailQuery ..|> IRequest : <<implements>>
GetQuestionSetDetailQueryHandler ..> GetQuestionSetDetailQuery :  <<uses>>
QuestionSetEndpoints ..> GetQuestionSetDetailQuery : <<uses>>
GetQuestionSetDetailQueryHandler ..|> IRequestHandler : <<implements>>
GetQuestionSetDetailQueryHandler ..> QuestionSetDetailDto : <<uses>>
'=====INJECT
GetQuestionSetDetailQueryHandler ..> IQuestionSetService : <<inject>>
GetQuestionSetDetailQueryHandler ..> IUser : <<inject>>
'=====INJECT
@enduml