@startuml

'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/Service/IUser.puml
!include ../Services/IQuestionSetService.puml
'=====================COMMAND========================
class UpdateQuestionSetHistoryCommand {
    + QuestionSetId : Guid
    + Questions : List<QuestionHistoryUpdate>
}

class QuestionHistoryUpdate {
    + QuestionId : Guid
    + IsCorrect : bool
}

class UpdateQuestionSetHistoryCommandHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    -  _questionSetService : IQuestionSetService
    + UpdateQuestionSetHistoryCommandHandler(context:IApplicationDbContext, user:IUser, questionSetService:IQuestionSetService)
    +  Handle(request:UpdateQuestionSetHistoryCommand, cancellationToken:CancellationToken) : Task<Unit>
}
'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    +  UpdateQuestionSetHistory(questionSetId:Guid, questions:List<QuestionHistoryUpdate>, sender:ISender) : Task<Ok<ApiResponse<Unit>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
UpdateQuestionSetHistoryCommand ..|> IRequest : <<implements>>
UpdateQuestionSetHistoryCommandHandler ..> UpdateQuestionSetHistoryCommand :  <<uses>>
QuestionSetEndpoints ..> UpdateQuestionSetHistoryCommand : <<uses>>
UpdateQuestionSetHistoryCommandHandler ..|> IRequestHandler : <<implements>>
UpdateQuestionSetHistoryCommand --* QuestionHistoryUpdate : <<uses>>
'=====INJECT
UpdateQuestionSetHistoryCommandHandler ..> IQuestionSetService : <<inject>>
UpdateQuestionSetHistoryCommandHandler ..> IUser : <<inject>>
UpdateQuestionSetHistoryCommandHandler ..> IApplicationDbContext : <<inject>>
'=====INJECT
@enduml