@startuml
title QuestionSet | UpdateQuestionSetCommand
'=====================DEFINE========================
!define QUESTIONSET_SERVICE_CANUSEREDIT
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/Service/IUser.puml
!include ../Services/IQuestionSetService.puml
!include ../dtos/CreateUpdateQuestionDto.puml
'=====================COMMAND========================
class UpdateQuestionSetCommand {
    + QuestionSetId : Guid
    + Name : string?
    + Description : string?
    + CreateUpdateQuestions : List<CreateUpdateQuestionDto>
    + DeleteQuestionIds : List<Guid>
}

class UpdateQuestionSetCommandHandler {
    -  _dbContext : IApplicationDbContext
    -  _questionSetService : IQuestionSetService
    -  _currentUser : IUser
    + UpdateQuestionSetCommandHandler(dbContext:IApplicationDbContext, questionSetService:IQuestionSetService, currentUser:IUser)
    +  Handle(request:UpdateQuestionSetCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class QuestionSetEndpoints  {
    +  UpdateQuestionSet(questionSetId:Guid, command:UpdateQuestionSetCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
UpdateQuestionSetCommand ..|> IRequest : <<implements>>
UpdateQuestionSetCommandHandler ..> UpdateQuestionSetCommand :  <<uses>>
QuestionSetEndpoints ..> UpdateQuestionSetCommand : <<uses>>
UpdateQuestionSetCommandHandler ..|> IRequestHandler : <<implements>>
'=====INJECT
UpdateQuestionSetCommandHandler ..> IApplicationDbContext : <<inject>>
UpdateQuestionSetCommandHandler ..> IQuestionSetService : <<inject>>
UpdateQuestionSetCommandHandler ..> IUser : <<inject>>
'=====END INJECT
UpdateQuestionSetCommand --* CreateUpdateQuestionDto 
@enduml