@startuml
interface IUser {
    UserId : Guid?
}

class CurrentUser {
    -_httpContextAccessor : IHttpContextAccessor
    + CurrentUser(httpContextAccessor:IHttpContextAccessor)
    + UserId : Guid?
}
IUser <|-- CurrentUser
@enduml
