@startuml
class CreateMultipleChoiceDto {
    + Text : string?
    + IsAnswer : bool
}
class CreateMatchingPairDto {
    + LeftItem : string?
    + RightItem : string?
}
class CreateOrderingItemDto {
    + Text : string?
    + CorrectOrder : int
}
class CreateUpdateQuestionDto {
    + QuestionId : Guid?
    + Type : string?
    + QuestionText : string?
    + ExplainText : string?
    + <<required>> Score : float
    + MultipleChoices : List<CreateMultipleChoiceDto>?
    + MatchingPairs : List<CreateMatchingPairDto>?
    + OrderingItems : List<CreateOrderingItemDto>?
    + ShortAnswer : string?
}

CreateUpdateQuestionDto *-- CreateMultipleChoiceDto
CreateUpdateQuestionDto *-- CreateMatchingPairDto
CreateUpdateQuestionDto *-- CreateOrderingItemDto
@enduml
