@startuml
interface IFolderTestService {
    !ifdef FOLDER_TEST_SERVICE_CANDELETEOREDITFOLDERTEST
    +  CanDeleteOrEditFolderTest(folderTestId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef FOLDER_TEST_SERVICE_ISOWNEROREDITOR
    +  IsOwnerOrEditor(folderTestId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef FOLDER_TEST_SERVICE_TRYCANUSETESTEMPLATE
    +  TryCanUseTesTemplate(testTemplateId:Guid): Task
    !endif
}

'class FolderTestService {
'    -  _context : IApplicationDbContext
'    -  _identityService : IIdentityService
'    -  _user : IUser
'    + FolderTestService(context:IApplicationDbContext, user:IUser, identityService:IIdentityService)
'    +  CanDeleteOrEditFolderTest(folderTestId:Guid, cancellationToken:CancellationToken): Task<bool>
'    +  IsOwnerOrEditor(folderTestId:Guid, cancellationToken:CancellationToken): Task<bool>
'    +  TryCanUseTesTemplate(testTemplateId:Guid): Task
'}

IFolderTestService <|.. FolderTestService : <<implements>>
@enduml