@startuml
actor User
participant "Change password UI" as UI
participant AuthenticationEndpoints
participant ChangePasswordHandler
participant IdentityService
participant UserManager
Database Database

User -> UI : Enter old password, new password, click confirm
activate UI
UI -> AuthenticationEndpoints : POST /api/Authentication/ChangePassword
activate AuthenticationEndpoints
AuthenticationEndpoints -> ChangePasswordHandler : Send ChangePasswordCommand
activate ChangePasswordHandler
ChangePasswordHandler -> IdentityService : ChangePasswordAsync(userId, currentPassword, newPassword)
activate IdentityService
IdentityService -> UserManager : FindByIdAsync(userId)
activate UserManager
UserManager -> Database : Query UserAccount
activate Database
Database --> UserManager : UserAccount/null
deactivate Database
alt User not found
    UserManager --> IdentityService : Error: ACCOUNT_NOTFOUND
    deactivate UserManager
    IdentityService --> ChangePasswordHandler : Error: ACCOUNT_NOTFOUND
    ChangePasswordHandler --> AuthenticationEndpoints : Error (ACCOUNT_NOTFOUND)
    AuthenticationEndpoints --> UI : 400 Bad Request (ACCOUNT_NOTFOUND)
    UI -> User : Display error: Account not found
else User found
    IdentityService -> UserManager : ChangePasswordAsync(user, currentPassword, newPassword)
    activate UserManager
    UserManager -> IdentityService: IdentityResult
    deactivate UserManager
    alt Incorrect old password
        UserManager --> IdentityService : Error: ACCOUNT_WRONG_PASSWORD
        IdentityService --> ChangePasswordHandler : Error: ACCOUNT_WRONG_PASSWORD
        ChangePasswordHandler --> AuthenticationEndpoints : Error (ACCOUNT_WRONG_PASSWORD)
        AuthenticationEndpoints --> UI : 400 Bad Request (ACCOUNT_WRONG_PASSWORD)
        UI -> User : Display error: Incorrect old password
    else Success
        UserManager -> Database : Update UserAccount
        activate Database
        Database --> UserManager : Success
        deactivate Database
        UserManager --> IdentityService : Success
        deactivate UserManager
        IdentityService --> ChangePasswordHandler : Success
        ChangePasswordHandler --> AuthenticationEndpoints : Success
        AuthenticationEndpoints --> UI : 200 OK
        UI -> User : Display success message: Password changed successfully
    end
end
deactivate IdentityService
deactivate ChangePasswordHandler
deactivate AuthenticationEndpoints
deactivate UI
@enduml