@startuml
interface ICommentService {
    !ifdef COMMENT_SERVICE_CANCOMMENT_GUID
    +  CanComment(questionSetId:Guid): Task<bool>
    !endif
    !ifdef COMMENT_SERVICE_CANDELETE
    +  CanDelete(commentId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef COMMENT_SERVICE_CANCOMMENT_QUESTIONSET
    +  CanComment(questionSet:QuestionSet): Task<bool>
    !endif
}

class CommentService {
    -  _context : IApplicationDbContext
    -  _user : IUser
    + CommentService(context:IApplicationDbContext, user:IUser, identityService:IIdentityService)
    !ifdef COMMENT_SERVICE_CANCOMMENT_GUID
    +  CanComment(questionSetId:Guid): Task<bool>
    !endif
    !ifdef COMMENT_SERVICE_CANDELETE
    +  CanDelete(commentId:Guid, cancellationToken:CancellationToken): Task<bool>
    !endif
    !ifdef COMMENT_SERVICE_CANCOMMENT_QUESTIONSET
    +  CanComment(questionSet:QuestionSet): Task<bool>
    !endif
}

ICommentService <|.. CommentService : <<implements>>
@enduml