@startuml
!include ../../common/IApplicationDbContext.puml

class UserQuestionSetHistoryService {
    -  _context : IApplicationDbContext
    + UserQuestionSetHistoryService(context:IApplicationDbContext)
    +  DeleteHistoriesByUserAndSetAsync(userId:Guid, questionSetId:Guid, cancellationToken:CancellationToken) : Task
}
IUserQuestionSetHistoryService <|-- UserQuestionSetHistoryService
UserQuestionSetHistoryService ..> IApplicationDbContext : <<inject>>
@enduml
