@startuml
actor User
participant "Create Class UI" as UI <<UI>>
participant ClassEndpoints <<Controller>>
participant CreateClassCommandHandler <<Handler>>
participant ApplicationDbContext <<DbContext>>
participant Database

note right of CreateClassCommandHandler
  Managed by MediatR
end note

note right of ApplicationDbContext
  Managed by IoC
end note

User -> UI : Fill in info, click "Create"
activate UI
UI -> ClassEndpoints : POST /api/Class
activate ClassEndpoints
ClassEndpoints -> CreateClassCommandHandler : Handle(CreateClassCommand)
deactivate ClassEndpoints
activate CreateClassCommandHandler
CreateClassCommandHandler -> ApplicationDbContext : Add new Class
deactivate CreateClassCommandHandler
activate ApplicationDbContext
ApplicationDbContext -> Database : Insert new Class
deactivate ApplicationDbContext
activate Database
Database --> ApplicationDbContext : ClassId
deactivate Database
activate ApplicationDbContext
ApplicationDbContext --> CreateClassCommandHandler : Guid
deactivate ApplicationDbContext
activate CreateClassCommandHandler
CreateClassCommandHandler --> ClassEndpoints : Guid
deactivate CreateClassCommandHandler
activate ClassEndpoints
ClassEndpoints --> UI : 200 OK (ApiResponse<Guid>)
deactivate ClassEndpoints
UI -> User : Display info: Class created successfully
deactivate UI

@enduml