@startuml
actor User
participant "Class List UI" as UI <<UI>>
participant ":ClassEndpoints" as ClassEndpoints <<Controller>>
participant ":SearchClassQueryHandler" as SearchClassQueryHandler <<Handler>>
participant ":ApplicationDbContext" as ApplicationDbContext <<DbContext>>
participant Database

note right of SearchClassQueryHandler
  Managed by MediatR
end note

note right of ApplicationDbContext
  Managed by IoC
end note

User -> UI : Search for classes
activate UI
UI -> ClassEndpoints : GET /api/Class?name=...&shareMode=...
activate ClassEndpoints
ClassEndpoints -> SearchClassQueryHandler : Handle(SearchClassQuery)
deactivate ClassEndpoints
activate SearchClassQueryHandler
SearchClassQueryHandler -> ApplicationDbContext : Query Classes (not deleted, with CreatedByUser and ClassUsers)
deactivate SearchClassQueryHandler
activate ApplicationDbContext
ApplicationDbContext -> Database : Query Classes
deactivate ApplicationDbContext
activate Database
Database --> ApplicationDbContext : List<Class>
deactivate Database
activate ApplicationDbContext
ApplicationDbContext --> SearchClassQueryHandler : List<Class>
deactivate ApplicationDbContext
activate SearchClassQueryHandler

SearchClassQueryHandler -> ClassEndpoints : PaginatedList<ClassSearchResultDto>
deactivate SearchClassQueryHandler
activate ClassEndpoints
ClassEndpoints --> UI : 200 OK (ApiResponse<PaginatedList<ClassSearchResultDto>>)
deactivate ClassEndpoints
UI -> User : Show class search results
deactivate UI

@enduml