@startuml
class AttemptDetailDto {
    + AttemptId : Guid
    + Name : string?
    + TimeStart : DateTime
    + TimeEnd : DateTime
    + TimeLimit : int
    + TimeRemaining : double
    + Questions : List<QuestionAttemptDetailDto>
    + QuestionCount : int
}
@enduml