@startuml
'=====================DEFINE========================
!define TEST_SERVICE_CANVIEWOREDITTEST
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ITestService.puml
!include ../Dto/TestDetailDto.puml
!include ../../QuestionSets/Dtos/QuestionResponseDto.puml
'=====================QUERY========================
class GetTestDetailQuery {
    + TestId : Guid
    + IsShowQuestion : bool?
}

class GetTestDetailQueryHandler {
    -  _context : IApplicationDbContext
    -  _testService : ITestService
    + GetTestDetailQueryHandler(context:IApplicationDbContext, testService:ITestService)
    +  Handle(request:GetTestDetailQuery, cancellationToken:CancellationToken) : Task<TestDetailDto>
}

'=====================ENDPOINT========================
class TestEndpoints  {
    +  GetTestDetail(testId:Guid, isShowQuestion:bool?, sender:ISender) : Task<Ok<ApiResponse<TestDetailDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetTestDetailQuery ..|> IRequest : <<implements>>
GetTestDetailQueryHandler ..> GetTestDetailQuery :  <<uses>>
TestEndpoints ..> GetTestDetailQuery : <<uses>>
GetTestDetailQueryHandler ..|> IRequestHandler : <<implements>>
GetTestDetailQueryHandler ..> TestDetailDto : <<uses>>
GetTestDetailQueryHandler ..> QuestionResponseDto : <<uses>>

'=====INJECT
GetTestDetailQueryHandler ..> IApplicationDbContext : <<inject>>
GetTestDetailQueryHandler ..> ITestService : <<inject>>
'=====INJECT
@enduml