@startuml
title Test | GetUserTestHistoryQuery
'=====================DEFINE========================
!define TEST_SERVICE_CANVIEWHISTORYOFTEST
!define TEST_SERVICE_CANVIEWOREDITTEST
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ITestService.puml
!include ../../common/service/IUser.puml
!include ../../common/Models/PaginatedList.puml
!include ../Dto/HistoryTestDto.puml
'=====================QUERY========================
class GetUserTestHistoryQuery {
    + TestId : Guid
    + UserId : Guid?
    + IsPassed : bool?
    + PageNumber : int
    + PageSize : int
}

class GetUserTestHistoryQueryHandler {
    -  _context : IApplicationDbContext
    -  _testService : ITestService
    -  _user : IUser
    + GetUserTestHistoryQueryHandler(context:IApplicationDbContext, testService:ITestService, user:IUser)
    +  Handle(request:GetUserTestHistoryQuery, cancellationToken:CancellationToken) : Task<PaginatedList<HistoryTestDto>>
}

'=====================ENDPOINT========================
class TestEndpoints  {
    +  GetHistoryTest(testId:Guid, userId:Guid?, isPassed:bool?, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<HistoryTestDto>>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetUserTestHistoryQuery ..|> IRequest : <<implements>>
GetUserTestHistoryQueryHandler ..> GetUserTestHistoryQuery :  <<uses>>
TestEndpoints ..> GetUserTestHistoryQuery : <<uses>>
GetUserTestHistoryQueryHandler ..|> IRequestHandler : <<implements>>
GetUserTestHistoryQueryHandler ..> PaginatedList : <<uses>>
GetUserTestHistoryQueryHandler ..> HistoryTestDto : <<uses>>

'=====INJECT
GetUserTestHistoryQueryHandler ..> IApplicationDbContext : <<inject>>
GetUserTestHistoryQueryHandler ..> ITestService : <<inject>>
GetUserTestHistoryQueryHandler ..> IUser : <<inject>>
'=====INJECT
@enduml