@startuml

'=====================DEFINE========================
!define TEST_SERVICE_CANVIEWOREDITTEST
!define TEST_SERVICE_QUESTIONACCESSANDCOMPAREFORTEST
!define TEST_SERVICE_CHECKQUESTIONSFORUPDATE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ITestService.puml
!include ../../QuestionSets/Dtos/CreateUpdateQuestionDto.puml
!include ../Dto/CheckUpdateQuestion.puml
'=====================COMMAND========================
class UpdateTestCommand {
    + TestId : Guid
    + Name : string
    + TimeLimit : int
    + StartTime : DateTime
    + EndTime : DateTime
    + GradeAttemptMethod : string
    + GradeQuestionMethod : string
    + IsShowCorrectAnswerInReview : bool
    + IsAllowReviewAfterSubmit : bool
    + MaxAttempt : int
    + NumberOfShuffles : int
    + PassingScore : int
    + CreateUpdateQuestions : List<CreateUpdateQuestionDto>
    + DeleteQuestionIds : List<Guid>
}

class UpdateTestCommandHandler {
    -  _context : IApplicationDbContext
    -  _testService : ITestService
    + UpdateTestCommandHandler(context:IApplicationDbContext, testService:ITestService)
    +  Handle(request:UpdateTestCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class TestEndpoints  {
    +  EditTest(testId:Guid, rq:UpdateTestCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
UpdateTestCommand ..|> IRequest : <<implements>>
UpdateTestCommandHandler ..> UpdateTestCommand :  <<uses>>
TestEndpoints ..> UpdateTestCommand : <<uses>>
UpdateTestCommandHandler ..|> IRequestHandler : <<implements>>
UpdateTestCommandHandler ..> CreateUpdateQuestionDto : <<uses>>
UpdateTestCommandHandler ..> CheckUpdateQuestion : <<uses>>

'=====INJECT
UpdateTestCommandHandler ..> IApplicationDbContext : <<inject>>
UpdateTestCommandHandler ..> ITestService : <<inject>>
'=====INJECT
@enduml