@startuml

'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class CreateUpdatePlanCommand {
    + PlanId : Guid?
    + Name : string
    + Price : int
    + Duration : int
    + Unit : string
    + CanLearn : bool
    + CanOpenTest : bool
    + CanCopyOrImportQuestionSet : bool
    + IsActive : bool
}

class CreatePlanCommandHandler {
    -  _context : IApplicationDbContext
    -  _identityService : IIdentityService
    + CreatePlanCommandHandler(context:IApplicationDbContext, identityService:IIdentityService, user:IUser)
    +  Handle(request:CreateUpdatePlanCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class PlanEndpoints  {
    +  CreateUpdatePlan(rq:CreateUpdatePlanCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateUpdatePlanCommand ..|> IRequest : <<implements>>
CreatePlanCommandHandler ..> CreateUpdatePlanCommand :  <<uses>>
PlanEndpoints ..> CreateUpdatePlanCommand : <<uses>>
CreatePlanCommandHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
CreatePlanCommandHandler ..> IApplicationDbContext : <<inject>>
CreatePlanCommandHandler ..> IIdentityService : <<inject>>
'=====INJECT
@enduml