@startuml
title Plan | GetDetailPlanQuery
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Dto/PlanDetailDto.puml
'=====================QUERY========================
class GetDetailPlanQuery {
    + PlanId : Guid <<get>> <<init>>
}

class GetDetailPlanQueryHandler {
    - <<readonly>> _context : IApplicationDbContext
    + GetDetailPlanQueryHandler(context:IApplicationDbContext)
    + <<async>> Handle(request:GetDetailPlanQuery, cancellationToken:CancellationToken) : Task<PlanDetailDto>
}

'=====================ENDPOINT========================
class PlanEndpoints  {
    + <<async>> GetDetailPlan(planId:Guid, sender:ISender) : Task<Ok<ApiResponse<PlanDetailDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetDetailPlanQuery ..|> IRequest : <<implements>>
GetDetailPlanQueryHandler ..> GetDetailPlanQuery :  <<uses>>
PlanEndpoints ..> GetDetailPlanQuery : <<uses>>
GetDetailPlanQueryHandler ..|> IRequestHandler : <<implements>>
GetDetailPlanQueryHandler ..> PlanDetailDto : <<uses>>

'=====INJECT
GetDetailPlanQueryHandler ..> IApplicationDbContext : <<inject>>
'=====INJECT
@enduml