@startuml
title FolderTest | CreateFolderCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
'=====================COMMAND========================
class CreateFolderCommand {
    + FolderName : string <<get>> <<set>>
}

class CreateFolderCommandHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    + CreateFolderCommandHandler(context:IApplicationDbContext, user:IUser)
    + <<async>> Handle(request:CreateFolderCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class FolderEndpoints  {
    + <<async>> CreateFolder(rq:CreateFolderCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include ./zCommon.puml
CreateFolderCommand ..|> IRequest : <<implements>>
CreateFolderCommandHandler ..> CreateFolderCommand :  <<uses>>
FolderEndpoints ..> CreateFolderCommand : <<uses>>
CreateFolderCommandHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
CreateFolderCommandHandler ..> IApplicationDbContext : <<inject>>
CreateFolderCommandHandler ..> IUser : <<inject>>
'=====INJECT
@enduml