@startuml

'=====================DEFINE========================
!define FOLDER_TEST_SERVICE_ISOWNEROREDITOR
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IFolderTestService.puml
!include /Dto/ResourceShareDto.puml
'=====================QUERY========================
class GetSharingInFolderQuery {
    + FolderId : Guid
}

class GetSharingInFolderQueryHandler {
    -  _context : IApplicationDbContext
    -  _folderTestService : IFolderTestService
    + GetSharingInFolderQueryHandler(context:IApplicationDbContext, folderTestService:IFolderTestService)
    +  Handle(request:GetSharingInFolderQuery, cancellationToken:CancellationToken) : Task<ResourceShareDto>
}

'=====================ENDPOINT========================
class FolderEndpoints  {
    +  GetSharingInFolder(folderId:Guid, sender:ISender) : Task<Ok<ApiResponse<ResourceShareDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetSharingInFolderQuery ..|> IRequest : <<implements>>
GetSharingInFolderQueryHandler ..> GetSharingInFolderQuery :  <<uses>>
FolderEndpoints ..> GetSharingInFolderQuery : <<uses>>
GetSharingInFolderQueryHandler ..|> IRequestHandler : <<implements>>
GetSharingInFolderQueryHandler ..> ResourceShareDto : <<uses>>

'=====INJECT
GetSharingInFolderQueryHandler ..> IApplicationDbContext : <<inject>>
GetSharingInFolderQueryHandler ..> IFolderTestService : <<inject>>
'=====INJECT
@enduml