@startuml

'=====================DEFINE========================
!define FOLDER_TEST_SERVICE_ISOWNEROREDITOR
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IFolderTestService.puml
'=====================COMMAND========================
class RemoveTestTemplateInFolderCommand {
    + FolderId : Guid
    + TestTemplateId : Guid
}

class RemoveTestTemplateInFolderCommandHandler {
    -  _context : IApplicationDbContext
    -  _folderTestService : IFolderTestService
    + RemoveTestTemplateInFolderCommandHandler(context:IApplicationDbContext, folderTestService:IFolderTestService)
    +  Handle(request:RemoveTestTemplateInFolderCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class FolderEndpoints  {
    +  RemoveTestTestTemplateInFolder(folderId:Guid, testTemplateId:Guid, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include ./zCommon.puml
RemoveTestTemplateInFolderCommand ..|> IRequest : <<implements>>
RemoveTestTemplateInFolderCommandHandler ..> RemoveTestTemplateInFolderCommand :  <<uses>>
FolderEndpoints ..> RemoveTestTemplateInFolderCommand : <<uses>>
RemoveTestTemplateInFolderCommandHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
RemoveTestTemplateInFolderCommandHandler ..> IApplicationDbContext : <<inject>>
RemoveTestTemplateInFolderCommandHandler ..> IFolderTestService : <<inject>>
'=====INJECT
@enduml