@startuml
title FolderTest | SearchFolderQuery
'=====================DEFINE========================
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include /Dto/SearchFolderTestDto.puml
'=====================QUERY========================
class SearchFolderQuery {
    + FolderName : string?
    + ShareMode : string?
    + PageNumber : int
    + PageSize : int
}

class SearchFolderQueryHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    + SearchFolderQueryHandler(context:IApplicationDbContext, user:IUser)
    +  Handle(request:SearchFolderQuery, cancellationToken:CancellationToken) : Task<PaginatedList<SearchFolderTestDto>>
}

'=====================ENDPOINT========================
class FolderEndpoints  {
    +  SearchFolderTest(folderName:string?, shareMode:string?, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<SearchFolderTestDto>>>>
}
'=====================RELATIONSHIP========================
!include ./zCommon.puml
SearchFolderQuery ..|> IRequest : <<implements>>
SearchFolderQueryHandler ..> SearchFolderQuery :  <<uses>>
FolderEndpoints ..> SearchFolderQuery : <<uses>>
SearchFolderQueryHandler ..|> IRequestHandler : <<implements>>
SearchFolderQueryHandler ..> SearchFolderTestDto : <<uses>>

'=====INJECT
SearchFolderQueryHandler ..> IApplicationDbContext : <<inject>>
SearchFolderQueryHandler ..> IUser : <<inject>>
'=====INJECT
@enduml