@startuml
title FolderTest | UpdateSharingInFolderCommand
'=====================DEFINE========================
!define FOLDER_TEST_SERVICE_ISOWNEROREDITOR
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IFolderTestService.puml
!include /Dto/UpsertSharingModelDto.puml
'=====================COMMAND========================
class UpdateSharingInFolderCommand {
    + FolderId : Guid
    + SharingModels : List<UpsertSharingModelDto>
    + DeleteUserIds : List<Guid>
}

class UpdateSharingInFolderCommandHandler {
    -  _context : IApplicationDbContext
    -  _folderTestService : IFolderTestService
    + UpdateSharingInFolderCommandHandler(context:IApplicationDbContext, folderTestService:IFolderTestService)
    +  Handle(request:UpdateSharingInFolderCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class FolderEndpoints  {
    +  UpdateSharingInFolder(folderId:Guid, rq:UpdateSharingInFolderCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include ./zCommon.puml
UpdateSharingInFolderCommand ..|> IRequest : <<implements>>
UpdateSharingInFolderCommandHandler ..> UpdateSharingInFolderCommand :  <<uses>>
FolderEndpoints ..> UpdateSharingInFolderCommand : <<uses>>
UpdateSharingInFolderCommandHandler ..|> IRequestHandler : <<implements>>
UpdateSharingInFolderCommandHandler ..> UpsertSharingModelDto : <<uses>>

'=====INJECT
UpdateSharingInFolderCommandHandler ..> IApplicationDbContext : <<inject>>
UpdateSharingInFolderCommandHandler ..> IFolderTestService : <<inject>>
'=====INJECT
@enduml