@startuml
title TestTemplates | CreateTestTemplateCommand
'=====================DEFINE========================
!define TEST_TEMPLATE_SERVICE_TRYCHECKQUESTIONACCESSFORTESTTEMPLATE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ITestTemplateService.puml
!include ../../QuestionSets/Dtos/CreateUpdateQuestionDto.puml
'=====================COMMAND========================
class CreateTestTemplateCommand {
    + Name : string
    + Description : string?
    + Questions : List<CreateUpdateQuestionDto>
}

class CreateTestTemplateCommandHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    -  _testTemplateService : ITestTemplateService
    + CreateTestTemplateCommandHandler(context:IApplicationDbContext, user:IUser, testTemplateService:ITestTemplateService)
    +  Handle(request:CreateTestTemplateCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class TestTemplateEndpoints  {
    +  CreateTestTemplate(rq:CreateTestTemplateCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateTestTemplateCommand ..|> IRequest : <<implements>>
CreateTestTemplateCommandHandler ..> CreateTestTemplateCommand :  <<uses>>
TestTemplateEndpoints ..> CreateTestTemplateCommand : <<uses>>
CreateTestTemplateCommandHandler ..|> IRequestHandler : <<implements>>
CreateTestTemplateCommandHandler ..> CreateUpdateQuestionDto : <<uses>>

'=====INJECT
CreateTestTemplateCommandHandler ..> IApplicationDbContext : <<inject>>
CreateTestTemplateCommandHandler ..> IUser : <<inject>>
CreateTestTemplateCommandHandler ..> ITestTemplateService : <<inject>>
'=====INJECT
@enduml