@startuml
title TestTemplates | CreateTestTemplateCommand
'=====================DEFINE========================
!define TEST_TEMPLATE_SERVICE_TRYCHECKQUESTIONACCESSFORTESTTEMPLATE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ITestTemplateService.puml
!include ../../QuestionSets/Dtos/CreateUpdateQuestionDto.puml
'=====================COMMAND========================
class CreateTestTemplateCommand {
    + Name : string <<get>> <<set>>
    + Description : string? <<get>> <<set>>
    + Questions : List<CreateUpdateQuestionDto> <<get>> <<set>>
}

class CreateTestTemplateCommandHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    - <<readonly>> _testTemplateService : ITestTemplateService
    + CreateTestTemplateCommandHandler(context:IApplicationDbContext, user:IUser, testTemplateService:ITestTemplateService)
    + <<async>> Handle(request:CreateTestTemplateCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class TestTemplateEndpoints  {
    + <<async>> CreateTestTemplate(rq:CreateTestTemplateCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateTestTemplateCommand ..|> IRequest : <<implements>>
CreateTestTemplateCommandHandler ..> CreateTestTemplateCommand :  <<uses>>
TestTemplateEndpoints ..> CreateTestTemplateCommand : <<uses>>
CreateTestTemplateCommandHandler ..|> IRequestHandler : <<implements>>
CreateTestTemplateCommandHandler ..> CreateUpdateQuestionDto : <<uses>>

'=====INJECT
CreateTestTemplateCommandHandler ..> IApplicationDbContext : <<inject>>
CreateTestTemplateCommandHandler ..> IUser : <<inject>>
CreateTestTemplateCommandHandler ..> ITestTemplateService : <<inject>>
'=====INJECT
@enduml