@startuml

'=====================DEFINE========================
!define TEST_TEMPLATE_SERVICE_CANDELETETESTTEMPLATE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ITestTemplateService.puml
'=====================COMMAND========================
class DeleteTestTemplateCommand {
    + TestTemplateId : Guid
}

class DeleteTestTemplateCommandHandler {
    -  _context : IApplicationDbContext
    -  _templateService : ITestTemplateService
    + DeleteTestTemplateCommandHandler(context:IApplicationDbContext, templateService:ITestTemplateService)
    +  Handle(request:DeleteTestTemplateCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class TestTemplateEndpoints  {
    +  DeleteTestTemplate(testTemplateId:Guid, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
DeleteTestTemplateCommand ..|> IRequest : <<implements>>
DeleteTestTemplateCommandHandler ..> DeleteTestTemplateCommand :  <<uses>>
TestTemplateEndpoints ..> DeleteTestTemplateCommand : <<uses>>
DeleteTestTemplateCommandHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
DeleteTestTemplateCommandHandler ..> IApplicationDbContext : <<inject>>
DeleteTestTemplateCommandHandler ..> ITestTemplateService : <<inject>>
'=====INJECT
@enduml