@startuml
title TestTemplates | ImportFileTestTemplateCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/Interfaces/IFileService.puml
!include ../../common/Models/FileStreamData.puml
!include ../Dto/ImportedQuestionDto.puml
'=====================COMMAND========================
class ImportFileTestTemplateCommand {
    + FileData : FileStreamData?
}

class ImportFileTestTemplateCommandHandler {
    -  _file : IFileService
    + ImportFileTestTemplateCommandHandler(file:IFileService)
    +  Handle(request:ImportFileTestTemplateCommand, cancellationToken:CancellationToken) : Task<ImportedQuestionDto>
}

'=====================ENDPOINT========================
class TestTemplateEndpoints  {
    +  ImportFileTestTemplate(file:IFormFile, sender:ISender) : Task<Ok<ApiResponse<ImportedQuestionDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
ImportFileTestTemplateCommand ..|> IRequest : <<implements>>
ImportFileTestTemplateCommandHandler ..> ImportFileTestTemplateCommand :  <<uses>>
TestTemplateEndpoints ..> ImportFileTestTemplateCommand : <<uses>>
ImportFileTestTemplateCommandHandler ..|> IRequestHandler : <<implements>>
ImportFileTestTemplateCommandHandler ..> ImportedQuestionDto : <<uses>>
ImportFileTestTemplateCommand *-- FileStreamData

'=====INJECT
ImportFileTestTemplateCommandHandler ..> IFileService : <<inject>>
'=====INJECT
@enduml