@startuml

'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include ../../common/Models/PaginatedList.puml
!include ../Dto/TestTemplateDto.puml
'=====================QUERY========================
class SearchTestTemplateQuery {
    + TestTemplateName : string?
    + ShareMode : string?
    + PageNumber : int
    + PageSize : int
}

class SearchTestTemplateQueryHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    + SearchTestTemplateQueryHandler(context:IApplicationDbContext, user:IUser)
    +  Handle(request:SearchTestTemplateQuery, cancellationToken:CancellationToken) : Task<PaginatedList<TestTemplateDto>>
}

'=====================ENDPOINT========================
class TestTemplateEndpoints  {
    +  SearchTestTemplate(name:string?, shareMode:string?, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<TestTemplateDto>>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
SearchTestTemplateQuery ..|> IRequest : <<implements>>
SearchTestTemplateQueryHandler ..> SearchTestTemplateQuery :  <<uses>>
TestTemplateEndpoints ..> SearchTestTemplateQuery : <<uses>>
SearchTestTemplateQueryHandler ..|> IRequestHandler : <<implements>>
SearchTestTemplateQueryHandler ..> PaginatedList : <<uses>>
SearchTestTemplateQueryHandler ..> TestTemplateDto : <<uses>>

'=====INJECT
SearchTestTemplateQueryHandler ..> IApplicationDbContext : <<inject>>
SearchTestTemplateQueryHandler ..> IUser : <<inject>>
'=====INJECT
@enduml