@startuml
title TestTemplates | SearchTestTemplateQuery
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include ../../common/Models/PaginatedList.puml
!include ../Dto/TestTemplateDto.puml
'=====================QUERY========================
class SearchTestTemplateQuery {
    + TestTemplateName : string? <<get>> <<set>>
    + ShareMode : string? <<get>> <<set>>
    + PageNumber : int <<get>> <<set>>
    + PageSize : int <<get>> <<set>>
}

class SearchTestTemplateQueryHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    + SearchTestTemplateQueryHandler(context:IApplicationDbContext, user:IUser)
    + <<async>> Handle(request:SearchTestTemplateQuery, cancellationToken:CancellationToken) : Task<PaginatedList<TestTemplateDto>>
}

'=====================ENDPOINT========================
class TestTemplateEndpoints  {
    + <<async>> SearchTestTemplate(name:string?, shareMode:string?, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<TestTemplateDto>>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
SearchTestTemplateQuery ..|> IRequest : <<implements>>
SearchTestTemplateQueryHandler ..> SearchTestTemplateQuery :  <<uses>>
TestTemplateEndpoints ..> SearchTestTemplateQuery : <<uses>>
SearchTestTemplateQueryHandler ..|> IRequestHandler : <<implements>>
SearchTestTemplateQueryHandler ..> PaginatedList : <<uses>>
SearchTestTemplateQueryHandler ..> TestTemplateDto : <<uses>>

'=====INJECT
SearchTestTemplateQueryHandler ..> IApplicationDbContext : <<inject>>
SearchTestTemplateQueryHandler ..> IUser : <<inject>>
'=====INJECT
@enduml