@startuml
actor User
participant "Question Detail UI" as UI
participant CommentEndpoints
participant CreateCommentCommandHandler as Handler
participant CommentService
participant ApplicationDbContext
participant Database

User -> UI : Enter comment, click "Post"
activate UI
UI -> CommentEndpoints : POST /api/Comment
activate CommentEndpoints
CommentEndpoints -> Handler : Handle(CreateCommentCommand)
activate Handler
Handler -> ApplicationDbContext : Query Question (Include QuestionSet) by QuestionId
activate ApplicationDbContext
ApplicationDbContext -> Database : Query Question, QuestionSet
activate Database
Database --> ApplicationDbContext : Question, QuestionSet
deactivate Database
ApplicationDbContext --> Handler : Question
deactivate ApplicationDbContext
alt Question Not Found or Cannot Comment
    Handler --> CommentEndpoints : Error: QUESTION_CAN_NOT_COMMENT
    CommentEndpoints --> UI : 400 Bad Request (errorCode: QUESTION_CAN_NOT_COMMENT)
    UI -> User : Error: Question not found or cannot comment
else Question Found
    Handler -> CommentService : CanComment(questionSetId)
    activate CommentService
    CommentService -> ApplicationDbContext : Query Permission 
    activate ApplicationDbContext
    ApplicationDbContext -> Database : Query Permission 
    activate Database
    Database --> ApplicationDbContext : Permission 
deactivate Database
    ApplicationDbContext --> CommentService : Permission 
deactivate ApplicationDbContext
    CommentService --> Handler : bool
deactivate CommentService
    alt No permission
        Handler --> CommentEndpoints : Error: USER_NOT_HAVE_PERMISSION_IN_COMMENT
        CommentEndpoints --> UI : 400 Bad Request (errorCode: USER_NOT_HAVE_PERMISSION_IN_COMMENT)
        UI -> User : Error: User does not have permission to comment
    else Allowed
        Handler -> ApplicationDbContext : Add new Comment
        activate ApplicationDbContext
        ApplicationDbContext -> Database : Insert Comment
        activate Database
        Database --> ApplicationDbContext : Success
deactivate Database
        ApplicationDbContext --> Handler : Guid
deactivate ApplicationDbContext
        Handler --> CommentEndpoints : Guid
        CommentEndpoints --> UI : 200 OK (ApiResponse<Guid>)
        UI -> User : Info: Comment posted successfully
    end
end
deactivate Handler
deactivate CommentEndpoints
deactivate UI
@enduml