@startuml
actor User
participant "Test Template List UI" as UI <<UI>>
participant ":TestTemplateEndpoints" as TestTemplateEndpoints <<Controller>>
participant ":SearchTestTemplateQueryHandler" as SearchTestTemplateQueryHandler <<Handler>>
participant ":ApplicationDbContext" as ApplicationDbContext <<DbContext>>
participant Database

note right of SearchTestTemplateQueryHandler
  Managed by MediatR
end note

note right of ApplicationDbContext
  Managed by IoC
end note

User -> UI : Search for test templates
activate UI
UI -> TestTemplateEndpoints : GET /api/TestTemplate?testTemplateName=...&shareMode=...
activate TestTemplateEndpoints
TestTemplateEndpoints -> SearchTestTemplateQueryHandler : Handle(SearchTestTemplateQuery)
deactivate TestTemplateEndpoints
activate SearchTestTemplateQueryHandler
SearchTestTemplateQueryHandler -> ApplicationDbContext : Query TestTemplateUsers (Include TestTemplate)
deactivate SearchTestTemplateQueryHandler
activate ApplicationDbContext
ApplicationDbContext -> Database : Query TestTemplateUsers, TestTemplate
deactivate ApplicationDbContext
activate Database
Database --> ApplicationDbContext : List<TestTemplateUser>
deactivate Database
activate ApplicationDbContext
ApplicationDbContext --> SearchTestTemplateQueryHandler : List<TestTemplateUser>
deactivate ApplicationDbContext
activate SearchTestTemplateQueryHandler
SearchTestTemplateQueryHandler -> TestTemplateEndpoints : PaginatedList<TestTemplateDto>
deactivate SearchTestTemplateQueryHandler
activate TestTemplateEndpoints
TestTemplateEndpoints --> UI : 200 OK (ApiResponse<PaginatedList<TestTemplateDto>>)
deactivate TestTemplateEndpoints
UI -> User : Show test template search results
deactivate UI

@enduml