@startuml
class ResourceShareDto {
    + Id : Guid <<get>> <<set>>
    + VisibilityMode : string? <<get>> <<set>>
    + SharingModel : List<SharingModelDto> <<get>> <<set>>
}

class SharingModelDto {
    + ShareMode : string? <<get>> <<set>>
    + UserId : Guid <<get>> <<set>>
    + FullName : string? <<get>> <<set>>
}
@enduml