@startuml

'=====================DEFINE========================
!define CLASS_SERVICE_ISLECTUREROROWNERINCLASS
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IClassService.puml
'=====================COMMAND========================
class ClassCodeDto {
    + Code : string
}

class CreateInviteCodeCommand {
    + ClassId : Guid?
    + ExpiredTime : double
}

class CreateInviteCodeCommandHandler {
    -  _context : IApplicationDbContext
    -  _classService : IClassService
    + CreateInviteCodeCommandHandler(context:IApplicationDbContext, classService:IClassService)
    +  Handle(request:CreateInviteCodeCommand, cancellationToken:CancellationToken) : Task<ClassCodeDto>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    +  CreateInviteCode(classId:Guid, rq:CreateInviteCodeCommand, sender:ISender) : Task<Ok<ApiResponse<ClassCodeDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateInviteCodeCommand ..|> IRequest : <<implements>>
CreateInviteCodeCommandHandler ..> CreateInviteCodeCommand :  <<uses>>
ClassEndpoints ..> CreateInviteCodeCommand : <<uses>>
CreateInviteCodeCommandHandler ..|> IRequestHandler : <<implements>>
CreateInviteCodeCommandHandler ..> ClassCodeDto : <<uses>>

'=====INJECT
CreateInviteCodeCommandHandler ..> IApplicationDbContext : <<inject>>
CreateInviteCodeCommandHandler ..> IClassService : <<inject>>
'=====INJECT
@enduml