@startuml
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
'=====================COMMAND========================
class CreateClassCommand {
    + Name : string
    + Topic : string?
}

class CreateClassCommandHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    + CreateClassCommandHandler(context:IApplicationDbContext, user:IUser)
    +  Handle(request:CreateClassCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    +  CreateClass(rq:CreateClassCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
CreateClassCommand ..|> IRequest : <<implements>>
CreateClassCommandHandler ..> CreateClassCommand :  <<uses>>
ClassEndpoints ..> CreateClassCommand : <<uses>>
CreateClassCommandHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
CreateClassCommandHandler ..> IApplicationDbContext : <<inject>>
CreateClassCommandHandler ..> IUser : <<inject>>
'=====INJECT
@enduml