@startuml
title Class | DeleteClassCommand
'=====================DEFINE========================
!define CLASS_SERVICE_GETCLASSOWNERACCESS
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IClassService.puml
'=====================COMMAND========================
class DeleteClassCommand {
    + ClassId : Guid <<get>> <<set>>
}

class DeleteClassHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _classService : IClassService
    + DeleteClassHandler(context:IApplicationDbContext, classService:IClassService)
    + <<async>> Handle(request:DeleteClassCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    + <<async>> DeleteClass(classId:Guid, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
DeleteClassCommand ..|> IRequest : <<implements>>
DeleteClassHandler ..> DeleteClassCommand :  <<uses>>
ClassEndpoints ..> DeleteClassCommand : <<uses>>
DeleteClassHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
DeleteClassHandler ..> IApplicationDbContext : <<inject>>
DeleteClassHandler ..> IClassService : <<inject>>
'=====INJECT
@enduml