@startuml

'=====================DEFINE========================
!define CLASS_SERVICE_ISUSERINCLASS
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IClassService.puml
'=====================QUERY========================
class ClassDetailDto {
    + ClassId : Guid
    + Name : string?
    + Topic : string?
}

class GetClassByIdQuery {
    + ClassId : Guid
}

class GetClassByIdQueryHandler {
    -  _context : IApplicationDbContext
    -  _classService : IClassService
    + GetClassByIdQueryHandler(context:IApplicationDbContext, classService:IClassService)
    +  Handle(request:GetClassByIdQuery, cancellationToken:CancellationToken) : Task<ClassDetailDto>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    +  GetClassById(classId:Guid, sender:ISender) : Task<Ok<ApiResponse<ClassDetailDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetClassByIdQuery ..|> IRequest : <<implements>>
GetClassByIdQueryHandler ..> GetClassByIdQuery :  <<uses>>
ClassEndpoints ..> GetClassByIdQuery : <<uses>>
GetClassByIdQueryHandler ..|> IRequestHandler : <<implements>>
GetClassByIdQueryHandler ..> ClassDetailDto : <<uses>>

'=====INJECT
GetClassByIdQueryHandler ..> IApplicationDbContext : <<inject>>
GetClassByIdQueryHandler ..> IClassService : <<inject>>
'=====INJECT
@enduml