@startuml

'=====================DEFINE========================
!define CLASS_SERVICE_ISUSERINCLASS
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include ../Service/IClassService.puml
'=====================QUERY========================
class GetUserPermissionInClassQuery {
    + ClassId : Guid
}

class GetUserPermissionInClassQueryHandler {
    -  _context : IApplicationDbContext
    -  _user : IUser
    -  _classService : IClassService
    + GetUserPermissionInClassQueryHandler(context:IApplicationDbContext, user:IUser, classService:IClassService)
    +  Handle(request:GetUserPermissionInClassQuery, cancellationToken:CancellationToken) : Task<string?>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    +  GetUserPermissionQuery(classId:Guid, sender:ISender) : Task<Ok<ApiResponse<string?>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetUserPermissionInClassQuery ..|> IRequest : <<implements>>
GetUserPermissionInClassQueryHandler ..> GetUserPermissionInClassQuery :  <<uses>>
ClassEndpoints ..> GetUserPermissionInClassQuery : <<uses>>
GetUserPermissionInClassQueryHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
GetUserPermissionInClassQueryHandler ..> IApplicationDbContext : <<inject>>
GetUserPermissionInClassQueryHandler ..> IUser : <<inject>>
GetUserPermissionInClassQueryHandler ..> IClassService : <<inject>>
'=====INJECT
@enduml