@startuml
title Class | GetUserPermissionInClassQuery
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include ../Service/IClassService.puml
'=====================QUERY========================
class GetUserPermissionInClassQuery {
    + ClassId : Guid <<get>> <<set>>
}

class GetUserPermissionInClassQueryHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    - <<readonly>> _classService : IClassService
    + GetUserPermissionInClassQueryHandler(context:IApplicationDbContext, user:IUser, classService:IClassService)
    + <<async>> Handle(request:GetUserPermissionInClassQuery, cancellationToken:CancellationToken) : Task<string?>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    + <<async>> GetUserPermissionQuery(classId:Guid, sender:ISender) : Task<Ok<ApiResponse<string?>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetUserPermissionInClassQuery ..|> IRequest : <<implements>>
GetUserPermissionInClassQueryHandler ..> GetUserPermissionInClassQuery :  <<uses>>
ClassEndpoints ..> GetUserPermissionInClassQuery : <<uses>>
GetUserPermissionInClassQueryHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
GetUserPermissionInClassQueryHandler ..> IApplicationDbContext : <<inject>>
GetUserPermissionInClassQueryHandler ..> IUser : <<inject>>
GetUserPermissionInClassQueryHandler ..> IClassService : <<inject>>
'=====INJECT
@enduml