@startuml
title Class | SearchClassQuery
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
!include ../../common/Models/PaginatedList.puml

'=====================QUERY========================
class ClassSearchResultDto {
    + ClassId : Guid
    + Name : string
    + OwnerId : Guid?
    + Owner : string?
    + Topic : string?
}

class SearchClassQuery {
    + ShareMode : string? <<get>> <<set>>
    + Name : string? <<get>> <<set>>
    + PageNumber : int <<get>> <<set>>
    + PageSize : int <<get>> <<set>>
}

class SearchClassQueryHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    + SearchClassQueryHandler(context:IApplicationDbContext, user:IUser)
    + <<async>> Handle(request:SearchClassQuery, cancellationToken:CancellationToken) : Task<PaginatedList<ClassSearchResultDto>>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    + <<async>> SearchClass(shareMode:string?, name:string?, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<ClassSearchResultDto>>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
SearchClassQuery ..|> IRequest : <<implements>>
SearchClassQueryHandler ..> SearchClassQuery :  <<uses>>
ClassEndpoints ..> SearchClassQuery : <<uses>>
SearchClassQueryHandler ..|> IRequestHandler : <<implements>>
SearchClassQueryHandler ..> PaginatedList : <<uses>>
SearchClassQueryHandler ..> ClassSearchResultDto : <<uses>>

'=====INJECT
SearchClassQueryHandler ..> IApplicationDbContext : <<inject>>
SearchClassQueryHandler ..> IUser : <<inject>>
'=====INJECT
@enduml