@startuml

'=====================DEFINE========================
!define CLASS_SERVICE_ISUSERINCLASS
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IClassService.puml
!include ../../common/Models/PaginatedList.puml
'=====================QUERY========================
class StudentSearchResultDto {
    + StudentId : Guid
    + FullName : string?
    + Email : string
    + Position : string?
}

class SearchStudentInClassQuery {
    + ClassId : Guid
    + Keyword : string?
    + FieldName : string?
    + PageNumber : int
    + PageSize : int
}

class SearchStudentInClassQueryHandler {
    -  _context : IApplicationDbContext
    -  _classService : IClassService
    + SearchStudentInClassQueryHandler(context:IApplicationDbContext, classService:IClassService)
    +  Handle(request:SearchStudentInClassQuery, cancellationToken:CancellationToken) : Task<PaginatedList<StudentSearchResultDto>>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    +  SearchStudent(classId:Guid, keyword:string?, fieldName:string?, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<StudentSearchResultDto>>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
SearchStudentInClassQuery ..|> IRequest : <<implements>>
SearchStudentInClassQueryHandler ..> SearchStudentInClassQuery :  <<uses>>
ClassEndpoints ..> SearchStudentInClassQuery : <<uses>>
SearchStudentInClassQueryHandler ..|> IRequestHandler : <<implements>>
SearchStudentInClassQueryHandler ..> PaginatedList : <<uses>>
SearchStudentInClassQueryHandler ..> StudentSearchResultDto : <<uses>>

'=====INJECT
SearchStudentInClassQueryHandler ..> IApplicationDbContext : <<inject>>
SearchStudentInClassQueryHandler ..> IClassService : <<inject>>
'=====INJECT
@enduml