@startuml
title Class | UpdateClassCommand
'=====================DEFINE========================
!define CLASS_SERVICE_GETCLASSOWNERACCESS
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/IClassService.puml
!include ../../common/service/IUser.puml
'=====================COMMAND========================
class UpdateClassCommand {
    + ClassId : Guid?
    + Name : string
    + Topic : string?
}

class UpdateClassCommandHandler {
    -  _context : IApplicationDbContext
    -  _classService : IClassService
    -  _user : IUser
    + UpdateClassCommandHandler(context:IApplicationDbContext, classService:IClassService, user:IUser)
    +  Handle(request:UpdateClassCommand, cancellationToken:CancellationToken) : Task<Guid>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    +  UpdateClass(classId:Guid, rq:UpdateClassCommand, sender:ISender) : Task<Ok<ApiResponse<Guid>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
UpdateClassCommand ..|> IRequest : <<implements>>
UpdateClassCommandHandler ..> UpdateClassCommand :  <<uses>>
ClassEndpoints ..> UpdateClassCommand : <<uses>>
UpdateClassCommandHandler ..|> IRequestHandler : <<implements>>

'=====INJECT
UpdateClassCommandHandler ..> IApplicationDbContext : <<inject>>
UpdateClassCommandHandler ..> IClassService : <<inject>>
UpdateClassCommandHandler ..> IUser : <<inject>>
'=====INJECT
@enduml