@startuml
title Class | UpdatePositionCommand
'=====================DEFINE========================

'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../../common/service/IUser.puml
'=====================COMMAND========================
class UpdatePositionDto {
    + Position : string
    + UserId : Guid
}

class UpdatePositionCommand {
    + ClassId : Guid? <<get>> <<set>>
    + UserId : Guid? <<get>> <<set>>
    + Position : string? <<get>> <<set>>
}

class UpdatePositionCommandHandler {
    - <<readonly>> _context : IApplicationDbContext
    - <<readonly>> _user : IUser
    + UpdatePositionCommandHandler(context:IApplicationDbContext, user:IUser)
    + <<async>> Handle(request:UpdatePositionCommand, cancellationToken:CancellationToken) : Task<UpdatePositionDto>
}

'=====================ENDPOINT========================
class ClassEndpoints  {
    + <<async>> UpdatePosition(classId:Guid, userId:Guid, rq:UpdatePositionCommand, sender:ISender) : Task<Ok<ApiResponse<UpdatePositionDto>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
UpdatePositionCommand ..|> IRequest : <<implements>>
UpdatePositionCommandHandler ..> UpdatePositionCommand :  <<uses>>
ClassEndpoints ..> UpdatePositionCommand : <<uses>>
UpdatePositionCommandHandler ..|> IRequestHandler : <<implements>>
UpdatePositionCommandHandler ..> UpdatePositionDto : <<uses>>

'=====INJECT
UpdatePositionCommandHandler ..> IApplicationDbContext : <<inject>>
UpdatePositionCommandHandler ..> IUser : <<inject>>
'=====INJECT
@enduml