@startuml
title Comment | GetCommentByQuestionQuery
'=====================DEFINE========================
!define COMMENT_SERVICE_CANCOMMENT_QUESTIONSET
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/IApplicationDbContext.puml
!include ../Service/ICommentService.puml
!include ../../common/Models/PaginatedList.puml
!include ../Dto/CommentDto.puml
'=====================QUERY========================
class GetCommentByQuestionQuery {
    + QuestionId : Guid
    + PageNumber : int
    + PageSize : int
}

class GetCommentByQuestionQueryHandler {
    -  _context : IApplicationDbContext
    -  _commentService : ICommentService
    -  _mapper : IMapper
    + GetCommentByQuestionQueryHandler(context:IApplicationDbContext, commentService:ICommentService, mapper:IMapper)
    +  Handle(request:GetCommentByQuestionQuery, cancellationToken:CancellationToken) : Task<PaginatedList<CommentDto>>
}

'=====================ENDPOINT========================
class CommentEndpoints  {
    +  GetComment(questionId:Guid, sender:ISender, pageNumber:int, pageSize:int) : Task<Ok<ApiResponse<PaginatedList<CommentDto>>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
GetCommentByQuestionQuery ..|> IRequest : <<implements>>
GetCommentByQuestionQueryHandler ..> GetCommentByQuestionQuery :  <<uses>>
CommentEndpoints ..> GetCommentByQuestionQuery : <<uses>>
GetCommentByQuestionQueryHandler ..|> IRequestHandler : <<implements>>
GetCommentByQuestionQueryHandler ..> PaginatedList : <<uses>>
GetCommentByQuestionQueryHandler ..> CommentDto : <<uses>>

'=====INJECT
GetCommentByQuestionQueryHandler ..> IApplicationDbContext : <<inject>>
GetCommentByQuestionQueryHandler ..> ICommentService : <<inject>>
GetCommentByQuestionQueryHandler ..> IMapper : <<inject>>
'=====INJECT
@enduml