@startuml

'=====================DEFINE========================
!define REQUEST_PASSWORD_RESET
!define EMAIL_SERVICE
'=====================IMPORT========================
!include ../../GlobalSettings.puml
!include ../../common/Mediatr.puml
!include ../../common/EndpointClasses.puml
!include ../../common/service/IIdentityService.puml
'=====================COMMAND========================
class RequestPasswordResetCommand {
    +Email : string
}
class RequestPasswordResetCommandHandler {
    -_identityService : IIdentityService
    +Handle(command: RequestPasswordResetCommand, cancellationToken: CancellationToken)
}
'=====================ENDPOINT========================
class AuthenticationEndpoints {
    +RequestPasswordReset(command: RequestPasswordResetCommand, sender: ISender) : Task<Ok<ApiResponse<object>>>
}
'=====================RELATIONSHIP========================
!include zCommon.puml
RequestPasswordResetCommand ..|> IRequest : <<implements>>
RequestPasswordResetCommandHandler ..> IIdentityService : <<inject>>
RequestPasswordResetCommandHandler ..> RequestPasswordResetCommand :  <<use>>
AuthenticationEndpoints ..> RequestPasswordResetCommand : <<use>>
RequestPasswordResetCommandHandler ..|> IRequestHandler : <<implements>>
@enduml